spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Soccer Coach
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true

server:
  contextPath: /
  port: 8080