server:
  contextPath: /
  port: 8081

# Config FEIGN
soccerCoach.feign.url: ${FEIGN_URL:localhost:8080/api/v1}
soccerCoach.feign.name: soccercoach-api
feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CON_TIMEOUT:1000}
        readTimeout: ${FEIGN_READ_TIMEOUT:6000}
        loggerLevel: ${FEIGN_LOGGER:basic}